parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint/eslint-plugin"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "prettier"
root: true
env:
    node: true
    mocha: true
rules:
    "@typescript-eslint/explicit-member-accessibility": error
    "@typescript-eslint/explicit-function-return-type": error
    "@typescript-eslint/method-signature-style": [ error, method ]
    "@typescript-eslint/prefer-for-of": error
    "@typescript-eslint/prefer-enum-initializers": error
    "@typescript-eslint/prefer-literal-enum-member": error
    "@typescript-eslint/prefer-optional-chain": error
    "@typescript-eslint/sort-type-union-intersection-members": error
    "@typescript-eslint/type-annotation-spacing": error
    "@typescript-eslint/unified-signatures": error
    no-console: warn